/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Nutri AI Food Calorie Tracker API
 * API для учёта и подсчёта калорий с возможностью ввода приёма пищи через ИИ
 * OpenAPI spec version: 1.0.0
 */

export interface User {
  id: string;
  email: string;
  passwordHash: string;
  displayName?: string;
  timezone?: string;
  /** @minimum 0 */
  dailyKcalGoal?: number;
  createdAt: string;
}

export interface DayEntry {
  id: string;
  userId: string;
  date: string;
  /** @minimum 0 */
  targetKcal?: number;
  /** @minimum 0 */
  consumedKcal?: number;
  notes?: string;
  createdAt: string;
  updatedAt: string;
  meals?: Meal[];
}

export type MealType = (typeof MealType)[keyof typeof MealType];

export const MealType = {
  breakfast: 'breakfast',
  lunch: 'lunch',
  dinner: 'dinner',
  snack: 'snack',
  other: 'other',
} as const;

export type MealSource = (typeof MealSource)[keyof typeof MealSource];

export const MealSource = {
  manual: 'manual',
  ai: 'ai',
} as const;

export interface Meal {
  id: string;
  dayEntryId: string;
  type: MealType;
  /** @pattern ^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$ */
  time?: string;
  name?: string;
  items?: FoodItem[];
  /** @minimum 0 */
  totalKcal: number;
  source: MealSource;
  /**
   * @minimum 0
   * @maximum 1
   */
  aiConfidence?: number;
  createdAt: string;
  updatedAt: string;
}

export interface FoodItem {
  id: string;
  mealId: string;
  name: string;
  quantity: number;
  unit: string;
  /** @minimum 0 */
  kcal: number;
  protein?: number;
  fat?: number;
  carbs?: number;
  source?: string;
}

export type DietPlanMacros = {
  proteinPct?: number;
  fatPct?: number;
  carbsPct?: number;
};

export interface DietPlan {
  id: string;
  /** @nullable */
  userId?: string | null;
  name: string;
  /** @minimum 0 */
  targetKcal: number;
  macros?: DietPlanMacros;
  description?: string;
  createdAt: string;
  updatedAt: string;
}

export type AiParseLogRequestPayload = { [key: string]: unknown };

export type AiParseLogResponsePayload = { [key: string]: unknown };

export interface AiParseLog {
  id: string;
  /** @nullable */
  userId?: string | null;
  requestText: string;
  requestPayload?: AiParseLogRequestPayload;
  responsePayload?: AiParseLogResponsePayload;
  responseTimeMs?: number;
  createdAt: string;
}

export interface CalendarDay {
  date: string;
  /** @minimum 0 */
  consumedKcal: number;
  /** @minimum 0 */
  targetKcal: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  consumedPercent: number;
}

export interface SignupRequest {
  email: string;
  /** @minLength 8 */
  password: string;
  displayName?: string;
  timezone?: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface GoogleAuthRequest {
  /** Google ID token from Gmail OAuth */
  idToken: string;
}

export interface AuthResponse {
  token?: string;
  user?: User;
}

export type CreateMealRequestType =
  (typeof CreateMealRequestType)[keyof typeof CreateMealRequestType];

export const CreateMealRequestType = {
  breakfast: 'breakfast',
  lunch: 'lunch',
  dinner: 'dinner',
  snack: 'snack',
  other: 'other',
} as const;

export type CreateMealRequestItemsItem = {
  name: string;
  quantity: number;
  unit: string;
  kcal: number;
  protein?: number;
  fat?: number;
  carbs?: number;
  source?: string;
};

export type CreateMealRequestSource =
  (typeof CreateMealRequestSource)[keyof typeof CreateMealRequestSource];

export const CreateMealRequestSource = {
  manual: 'manual',
  ai: 'ai',
} as const;

export interface CreateMealRequest {
  type: CreateMealRequestType;
  /** @pattern ^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$ */
  time?: string;
  name?: string;
  items?: CreateMealRequestItemsItem[];
  /** @minimum 0 */
  totalKcal: number;
  source: CreateMealRequestSource;
  /**
   * @minimum 0
   * @maximum 1
   */
  aiConfidence?: number;
}

export interface AiParseMealRequest {
  userId?: string;
  date?: string;
  /** @maxLength 2048 */
  text: string;
}

export type AiParseMealResponseParsedItemsItem = {
  name?: string;
  quantity?: number;
  unit?: string;
  kcal?: number;
  protein?: number;
  fat?: number;
  carbs?: number;
  /**
   * @minimum 0
   * @maximum 1
   */
  confidence?: number;
};

export interface AiParseMealResponse {
  parsedItems?: AiParseMealResponseParsedItemsItem[];
  /** @minimum 0 */
  totalKcal?: number;
  warnings?: string[];
}

export interface StatsResponse {
  from?: string;
  to?: string;
  totalKcal?: number;
  averageKcal?: number;
  averageGoalCompletion?: number;
  days?: CalendarDay[];
}

export type ErrorDetails = { [key: string]: unknown };

export interface Error {
  error?: string;
  message?: string;
  details?: ErrorDetails;
}

/**
 * Не авторизован
 */
export type UnauthorizedResponse = Error;

/**
 * Не найдено
 */
export type NotFoundResponse = Error;

/**
 * Некорректный запрос
 */
export type BadRequestResponse = Error;

export type GetCalendarParams = {
  /**
   * @pattern ^\d{4}-\d{2}$
   */
  month: string;
};

export type GetCalendar200 = {
  month?: string;
  days?: CalendarDay[];
};

export type GetPlans200 = {
  plans?: DietPlan[];
};

export type PostPlansIdApplyParams = {
  date?: string;
};

export type PostPlansIdApply200 = {
  message?: string;
  appliedTo?: string;
};

export type GetStatsParams = {
  from: string;
  to: string;
};
